version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install

  test_server:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Run Server Tests
          working_directory: ~/project/server
          command: npm test

  test_client:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install
      - run:
          name: Run Client Tests
          working_directory: ~/project/client
          command: npm test

workflows:
  version: 2
  test_pipeline:
    jobs:
      - install_dependencies
      - test_server:
          requires:
            - install_dependencies
      - test_client:
          requires:
            - install_dependencies
