version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
      - image: circleci/mongo:4.2.8
        environment:
          MONGO_INITDB_DATABASE: paymentsDB

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install || echo "No client package.json file found"

  test_server:
    executor: node-executor
    environment:
      DB_URI: mongodb://localhost:27017/paymentsDB
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Wait for MongoDB
          command: |
            for i in $(seq 1 10); do
              nc -z localhost 27017 && echo "MongoDB is ready" && break
              echo "Waiting for MongoDB to be ready..."
              sleep 3
            done
      - run:
          name: Run Server Tests
          working_directory: ~/project/server
          command: npm test -- --detectOpenHandles

  test_client:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install || echo "No client package.json file found"
      - run:
          name: Run Client Tests
          working_directory: ~/project/client
          command: npm test || echo "No client tests found"

  sonar_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Load Environment Variables
          command: source .env || echo "No .env file found"
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=APDS-POE \
              -Dsonar.sources=./server,./client \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=080954d5b147c561f538459ce3cfd55b7150d8a4 \
              -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/__tests__/**

workflows:
  version: 2
  test_pipeline:
    jobs:
      - install_dependencies
      - test_server:
          requires:
            - install_dependencies
      - test_client:
          requires:
            - install_dependencies
      - sonar_scan:
          requires:
            - install_dependencies
