version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
      - image: mongo:4.4
        name: mongo
        command: [--bind_ip_all]  # Ensure MongoDB is accessible within the CircleCI environment

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install || echo "No client package.json file found"

  test_server:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: npm install
      - run:
          name: Run Server Tests
          working_directory: ~/project/server
          environment:
            DB_URI: mongodb://localhost:27017/paymentsDB  # Use MongoDB URI for testing
          command: npm test

  test_client:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Client Dependencies
          working_directory: ~/project/client
          command: npm install || echo "No client package.json file found"
      - run:
          name: Run Client Tests
          working_directory: ~/project/client
          command: npm test || echo "No client tests found"

workflows:
  version: 2
  test_pipeline:
    jobs:
      - install_dependencies
      - test_server:
          requires:
            - install_dependencies
      - test_client:
          requires:
            - install_dependencies
